# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '50 10 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update
      run: python process.py
      run: python process_byosho.py
    - name: Set date
      run: echo ::set-env name=DATE::$(date +%F)
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: Update ${{ env.DATE }}
        files: covid.json byosho.json
        name: katsugeneration
        email: katsu.generation.888@gmail.com 

