# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Moving

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get -y install fonts-ipafont-gothic
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update
      run: python process_moving.py
    - name: Set date
      run: echo ::set-env name=DATE::$(date +%F)
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'feature/compare-moving'
        commit-message: Update Moving ${{ env.DATE }}
        files: moving_images/*.png
        name: katsugeneration
        email: katsu.generation.888@gmail.com 
